#!/usr/bin/env python3

import os
from pathlib import Path

IGNORE = [
    'tests/filters/feMorphology/huge-radius', # will timeout on CI
    'tests/structure/svg/negative-size', # invalid size
    'tests/structure/svg/no-size', # invalid size
    'tests/structure/svg/zero-size', # invalid size
    'tests/structure/svg/not-UTF-8-encoding', # invalid encoding
    # Produces slightly different output on some hardware.
    # Not a bug, just a SIMD rounding difference.
    'tests/paint-servers/radialGradient/focal-point-correction',
    
    # maybe vello-cpu bugs
    'tests/paint-servers/radialGradient/zero-r-with-stop-opacity-1',
    'tests/paint-servers/radialGradient/zero-r-with-stop-opacity-2',
    'tests/paint-servers/stop/stops-with-equal-offset-5',
    'tests/paint-servers/stop/stops-with-equal-offset-6',
    'tests/painting/stroke/control-points-clamping-1',
    'tests/painting/stroke-dasharray/0-n-with-round-caps',
    'tests/painting/stroke-dasharray/0-n-with-square-caps',
    'tests/painting/stroke/line-as-curve-1',
    'tests/painting/stroke/line-as-curve-2',
    'tests/painting/stroke-linecap/zero-length-path-with-round',
    'tests/painting/stroke-linecap/zero-length-path-with-square',
]

print('// Copyright 2020 the Resvg Authors')
print('// SPDX-License-Identifier: Apache-2.0 OR MIT')
print()
print('// This file is auto-generated by gen-tests.py')
print()
print('#![allow(non_snake_case)]')
print()
print('use crate::render;')
print()

files = sorted(list(Path('../../resvg/tests/tests').rglob('*.svg')))
for file in files:
    file = str(file).replace('.svg', '')
    file = file.removeprefix('../../resvg/tests/')

    if file in IGNORE:
        continue

    fn_name = file.replace('tests/', '')
    fn_name = fn_name.replace('/', '_')
    fn_name = fn_name.replace('-', '_')
    fn_name = fn_name.replace('=', '_eq_')
    fn_name = fn_name.replace('.', '_')
    fn_name = fn_name.replace('#', '')

    print(f'#[test] fn {fn_name}() {{ assert_eq!(render("{file}"), 0); }}')
