#!/usr/bin/env python3

"""Generate integration test files for resvg.

This script generates two test files:
- render.rs: Tests for all SVG files (unhinted rendering)
- render_hinted.rs: Tests for text SVG files (hinted rendering)

Usage:
    python3 gen-tests.py  # Uses default output paths
    python3 gen-tests.py -o custom/render.rs --output-hinted custom/render_hinted.rs
"""

import argparse
from pathlib import Path

IGNORE = [
    'tests/filters/feMorphology/huge-radius', # will timeout on CI
    'tests/structure/svg/negative-size', # invalid size
    'tests/structure/svg/no-size', # invalid size
    'tests/structure/svg/zero-size', # invalid size
    'tests/structure/svg/not-UTF-8-encoding', # invalid encoding
    # Produces slightly different output on some hardware.
    # Not a bug, just a SIMD rounding difference.
    'tests/paint-servers/radialGradient/focal-point-correction',
]


def make_fn_name(file_path):
    """Convert a file path to a valid Rust function name."""
    fn_name = file_path.replace('tests/', '')
    fn_name = fn_name.replace('/', '_')
    fn_name = fn_name.replace('-', '_')
    fn_name = fn_name.replace('=', '_eq_')
    fn_name = fn_name.replace('.', '_')
    fn_name = fn_name.replace('#', '')
    return fn_name


def generate_render_rs(output_file):
    """Generate render.rs with unhinted tests for all SVG files."""
    with open(output_file, 'w') as f:
        f.write('// Copyright 2020 the Resvg Authors\n')
        f.write('// SPDX-License-Identifier: Apache-2.0 OR MIT\n')
        f.write('\n')
        f.write('// This file is auto-generated by gen-tests.py\n')
        f.write('\n')
        f.write('#![allow(non_snake_case)]\n')
        f.write('\n')
        f.write('use crate::render;\n')
        f.write('\n')

        files = sorted(list(Path('tests').rglob('*.svg')))
        for file in files:
            file_str = str(file).replace('.svg', '')

            if file_str in IGNORE:
                continue

            fn_name = make_fn_name(file_str)
            f.write(f'#[test] fn {fn_name}() {{ assert_eq!(render("{file_str}"), 0); }}\n')


def generate_render_hinted_rs(output_file):
    """Generate render_hinted.rs with hinted tests for text SVG files."""
    with open(output_file, 'w') as f:
        f.write('// Copyright 2020 the Resvg Authors\n')
        f.write('// SPDX-License-Identifier: Apache-2.0 OR MIT\n')
        f.write('\n')
        f.write('// This file is auto-generated by gen-tests.py\n')
        f.write('\n')
        f.write('#![allow(non_snake_case)]\n')
        f.write('\n')
        f.write('use crate::render_hinted;\n')
        f.write('\n')

        # Only generate hinted tests for text-related tests
        text_files = sorted(list(Path('tests/text').rglob('*.svg')))
        for file in text_files:
            file_str = str(file).replace('.svg', '')

            if file_str in IGNORE:
                continue

            fn_name = 'hinted_' + make_fn_name(file_str)
            f.write(f'#[test] fn {fn_name}() {{ assert_eq!(render_hinted("{file_str}"), 0); }}\n')


def main():
    parser = argparse.ArgumentParser(
        description='Generate integration test files for resvg'
    )
    parser.add_argument(
        '--output', '-o',
        default='integration/render.rs',
        help='Output file for unhinted tests (default: integration/render.rs)'
    )
    parser.add_argument(
        '--output-hinted',
        default='integration/render_hinted.rs',
        help='Output file for hinted tests (default: integration/render_hinted.rs)'
    )
    args = parser.parse_args()

    generate_render_rs(args.output)
    print(f'Generated {args.output}')

    generate_render_hinted_rs(args.output_hinted)
    print(f'Generated {args.output_hinted}')


if __name__ == '__main__':
    main()
